version: '3.8'

services:
  backend:
    build:
      context: ./backend # Path to the backend Dockerfile
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    env_file:
      - ./backend/.env # Load environment variables from this file
    depends_on:
      - mongo # Tell the backend to wait for the database to start

  frontend:
    build:
      context: ./frontend # Path to the frontend Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    env_file:
      - ./frontend/.env # Load environment variables from this file
    depends_on:
      - backend # Tell the frontend to wait for the backend

  mongo:
    image: mongo:latest # Use the official MongoDB image
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persist database data

volumes:
  mongo-data: